name: smoketest

on:
  pull_request:
  push:
    branches:
      - develop

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2

      - name: Run setup-nextmv action
        uses: ./

      - name: Verify Nextmv CLI is available
        run: |
          nextmv version

  test-action-with-api-key:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2

      - name: Run setup-nextmv action with API key
        uses: ./
        with:
          api-key: ${{ secrets.API_KEY_PROD }}

      - name: Verify Nextmv CLI is available and configured
        run: |
          nextmv version
          nextmv cloud app exists -a nextroute

  test-action-with-custom-endpoint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2

      - name: Run setup-nextmv action with API key and custom endpoint
        uses: ./
        with:
          api-key: ${{ secrets.API_KEY_STAGING }}
          endpoint: ${{ secrets.ENDPOINT_STAGING }}

      - name: Verify Nextmv CLI is available and configured
        run: |
          nextmv version
          nextmv cloud app exists -a nextroute

  test-action-with-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2

      - name: Run setup-nextmv action with specific version
        uses: ./
        with:
          version: "v1.2.2"

      - name: Verify Nextmv CLI is available and at specified version
        run: |
          nextmv version

  test-action-with-uv-already-installed:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2

      - name: Install uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b  # v8.1.0

      - name: Run setup-nextmv action when uv is already installed
        uses: ./

      - name: Verify Nextmv CLI is available
        run: |
          nextmv version
